[workspace]
members = [
    "src/ckb_vm_glue",
    "src/ckb_vm_syscall",
    "src/example_bot",
    "src/ff_rt",
    "src/ff_local",
    "src/ff_web_common",
]

[profile.dev]
incremental = false
codegen-units = 1
